### ISSUE TITLE
Trouble installing

### ISSUE THREAD

**Issue by jonbell-lot23** [angrysql/hypertextual#3]
- Got an account at heroku.com, installed toolbelt, got all dependencies
- Heroku login, keys:add, and create seem to work
- When I type "git push heroic master" it says:
  fatal: Not a git repository (or any of the parent directories): .git 

Any idea what's going wrong?

**Comment by jmpavlick** [comment]
Well, if you typed `git push heroic master`, that's not going to work; it should be `git push heroku master`.

Secondly - after you clone the project down, you need to `cd` to the project folder before running `heroku create` and `git push heroku master`. I failed to include that in the documentation.

Try that and let me know if it works - if it does, I'll update the README.md.

**Comment by jonbell-lot23** [comment]
Got it working. I wasn't typing "heroic," that was just a typo in this comment.

I was in the right directory, but the bigger issue is I forgot to install bundler. Once I got that working, everything worked great. (but I agree, adding that cd into the docs sounds like a good idea)

Thanks!

**Comment by jmpavlick** [comment]
Thanks for letting me know.

Is Bundler a dependency for Heroku? I would have thought that anything needed for a Heroku deployment would come with the Toolbelt installer.

**Comment by jonbell-lot23** [comment]
Good question - I wasn't being super scientific, but my log shows it failing before Bundler and succeeding after it, so that seems to be what changed.
